"""Email notification sender for daily briefs."""

import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from datetime import datetime
from typing import List, Dict

from src.config import Config

logger = logging.getLogger(__name__)


class EmailSender:
    """Sends email notifications with task briefs."""

    def __init__(self):
        """Initialize the email sender."""
        self.smtp_server = Config.EMAIL_SMTP_SERVER
        self.smtp_port = Config.EMAIL_SMTP_PORT
        self.from_email = Config.EMAIL_FROM
        self.to_email = Config.EMAIL_TO
        self.password = Config.EMAIL_PASSWORD

    def send_daily_brief(self, brief_path: str, top_tasks: List[Dict]) -> bool:
        """
        Send daily brief via email.

        Args:
            brief_path: Path to the markdown brief file.
            top_tasks: List of top priority tasks.

        Returns:
            True if successful, False otherwise.
        """
        try:
            # Read the brief content
            with open(brief_path, 'r', encoding='utf-8') as f:
                markdown_content = f.read()

            # Create email message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = f"🎯 Your Daily Task Brief - {datetime.now().strftime('%B %d, %Y')}"
            msg['From'] = self.from_email
            msg['To'] = self.to_email

            # Create plain text version
            text_content = self._create_text_version(top_tasks, markdown_content)

            # Create HTML version
            html_content = self._create_html_version(top_tasks, markdown_content)

            # Attach both versions
            part1 = MIMEText(text_content, 'plain')
            part2 = MIMEText(html_content, 'html')
            msg.attach(part1)
            msg.attach(part2)

            # Send email
            logger.info(f"Sending email to {self.to_email}")
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.from_email, self.password)
                server.send_message(msg)

            logger.info("Email sent successfully")
            return True

        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False

    def _create_text_version(self, top_tasks: List[Dict], full_content: str) -> str:
        """Create plain text email version."""
        lines = []
        lines.append(f"Daily Task Brief - {datetime.now().strftime('%B %d, %Y')}")
        lines.append("=" * 60)
        lines.append("")
        lines.append("🎯 TOP PRIORITIES FOR TODAY")
        lines.append("")

        for i, item in enumerate(top_tasks[:5], 1):
            task = item['task']
            analysis = item['analysis']
            score = item['priority_score']

            lines.append(f"{i}. [{score:.1f}] {task['title']}")
            lines.append(f"   Summary: {analysis.get('summary', 'N/A')}")
            lines.append(f"   Action: {analysis.get('suggested_action', 'N/A')}")
            lines.append(f"   Time: {analysis.get('estimated_time_minutes', 'N/A')} minutes")
            lines.append("")

        lines.append("-" * 60)
        lines.append("")
        lines.append("Full brief is attached above.")
        lines.append("")
        lines.append("Have a productive day!")
        lines.append("")
        lines.append("---")
        lines.append("Generated by Microsoft To Do AI Task Manager")

        return "\n".join(lines)

    def _create_html_version(self, top_tasks: List[Dict], markdown_content: str) -> str:
        """Create HTML email version."""
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }}
        .task {{
            background-color: #f8f9fa;
            padding: 15px;
            margin-bottom: 15px;
            border-left: 4px solid #3498db;
            border-radius: 4px;
        }}
        .task-title {{
            font-size: 18px;
            font-weight: bold;
            color: #2c3e50;
            margin-bottom: 8px;
        }}
        .task-score {{
            display: inline-block;
            background-color: #3498db;
            color: white;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 14px;
            font-weight: bold;
            margin-right: 10px;
        }}
        .task-score.high {{
            background-color: #e74c3c;
        }}
        .task-score.medium {{
            background-color: #f39c12;
        }}
        .task-score.low {{
            background-color: #27ae60;
        }}
        .task-detail {{
            margin: 5px 0;
            padding-left: 10px;
        }}
        .task-detail strong {{
            color: #555;
        }}
        .footer {{
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #777;
            font-size: 14px;
        }}
        .emoji {{
            font-size: 24px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🎯 Your Daily Task Brief</h1>
        <p style="color: #777; font-size: 14px;">{datetime.now().strftime('%A, %B %d, %Y')}</p>

        <h2>Top Priorities for Today</h2>
"""

        for i, item in enumerate(top_tasks[:5], 1):
            task = item['task']
            analysis = item['analysis']
            score = item['priority_score']

            # Determine score class
            score_class = "high" if score >= 80 else "medium" if score >= 60 else "low"

            html += f"""
        <div class="task">
            <div class="task-title">
                {i}. <span class="task-score {score_class}">{score:.1f}</span> {task['title']}
            </div>
            <div class="task-detail"><strong>Summary:</strong> {analysis.get('summary', 'N/A')}</div>
            <div class="task-detail"><strong>Next Action:</strong> {analysis.get('suggested_action', 'N/A')}</div>
            <div class="task-detail"><strong>Estimated Time:</strong> {analysis.get('estimated_time_minutes', 'N/A')} minutes</div>
"""

            # Add "Why it matters" if available
            why_it_matters = analysis.get('why_it_matters')
            if why_it_matters:
                html += f"""
            <div class="task-detail" style="background-color: #e8f5e9; padding: 8px; border-left: 3px solid #4caf50; margin: 8px 0;">
                <strong>💡 Why this matters to you:</strong> {why_it_matters}
            </div>
"""

            # Add due date if available
            if task.get('due_date'):
                html += f"""
            <div class="task-detail"><strong>Due:</strong> {task['due_date']}</div>
"""

            # Add tags if available
            tags = analysis.get('tags', [])
            if tags:
                html += f"""
            <div class="task-detail"><strong>Tags:</strong> {', '.join(tags[:5])}</div>
"""

            # Add URLs if available
            urls = task.get('urls', [])
            if urls:
                html += """
            <div class="task-detail"><strong>Links:</strong><br>
"""
                for url in urls[:3]:  # Max 3 URLs
                    html += f"""
                <a href="{url}" style="color: #3498db; text-decoration: none; display: block; margin: 3px 0;">{url[:60]}{'...' if len(url) > 60 else ''}</a>
"""
                html += """
            </div>
"""

            html += """
        </div>
"""

        html += """
        <div class="footer">
            <p>📊 Full detailed brief is available in your output folder</p>
            <p style="margin-top: 15px;">
                <em>Generated by Microsoft To Do AI Task Manager</em><br>
                Powered by AI • Automated Daily
            </p>
        </div>
    </div>
</body>
</html>
"""

        return html

    def send_test_email(self) -> bool:
        """
        Send a test email to verify configuration.

        Returns:
            True if successful, False otherwise.
        """
        try:
            msg = MIMEText("This is a test email from your Microsoft To Do AI Task Manager.\n\nConfiguration is working correctly!")
            msg['Subject'] = "Test Email - Microsoft To Do AI Task Manager"
            msg['From'] = self.from_email
            msg['To'] = self.to_email

            logger.info(f"Sending test email to {self.to_email}")
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.from_email, self.password)
                server.send_message(msg)

            logger.info("Test email sent successfully")
            return True

        except Exception as e:
            logger.error(f"Failed to send test email: {e}")
            return False
